default: &default
  adapter:  mysql2
  encoding: utf8
  username: <%= ENV['CHAT_DB_USERNAME'] %>
  password: <%= ENV['CHAT_DB_PASSWORD'] %>
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port:     3306
  host:     localhost

test:
  <<: *default
  database: jotaay_test

development:
  <<: *default
  database: jotaay

## TODO investigate why using Rails.application.credentials.send(Rails.env) failing on test env
staging:
  <<: *default
  database: <%= Rails.application.credentials.staging&.dig(:database, :database) %>
  username: <%= Rails.application.credentials.staging&.dig(:database, :username) %>
  password: <%= Rails.application.credentials.staging&.dig(:database, :password) %>
  host:     <%= Rails.application.credentials.staging&.dig(:database, :host) %>
  port:     <%= Rails.application.credentials.staging&.dig(:database, :port) %>

production:
  <<: *default
