default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development: &develop
  <<: *default
  host:     localhost
  database: jotaay
  username: jotaay

test:
  <<: *develop
  database: jotaay_test

## TODO investigate why using Rails.application.credentials.send(Rails.env) failing on test env
staging:
  <<: *default
  database: <%= Rails.application.credentials.staging&.dig(:database, :database) %>
  username: <%= Rails.application.credentials.staging&.dig(:database, :username) %>
  password: <%= Rails.application.credentials.staging&.dig(:database, :password) %>
  host:     <%= Rails.application.credentials.staging&.dig(:database, :host) %>

production:
  <<: *default
