default: &default
  adapter: mysql2
  encoding: utf8
  database: <%= Rails.application.credentials.send(Rails.env).dig(:database, :database) %>
  username: <%= Rails.application.credentials.send(Rails.env).dig(:database, :username) %>
  password: <%= Rails.application.credentials.send(Rails.env).dig(:database, :password) %>
  host:     <%= Rails.application.credentials.send(Rails.env).dig(:database, :host) %>
  port:     <%= Rails.application.credentials.send(Rails.env).dig(:database, :port) %>
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

staging:
  <<: *default

production:
  <<: *default

test:
  <<: *default
  database: jotaay_test